# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da11b4b2c2f9b194926e0304f3a6f68b8c691b9dafda68a64b4a92744d9eca68892d62a24926058a9f98a748ecc8dd84d6f5a9197330e84103493d41ca07d4fe

test:
  secret_key_base: f30c8a345947711734dd1183cb5ecf516add996d3ecf17eaa505ce612c1e64ab706097ebf2a1bed7d2f6fb54de7b3ab6773c85e0a2b0cf87b6e48b52ad3895b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
